DROP table if EXISTS cmp_order;
CREATE TABLE `cmp_order` (
  `orderNo` varchar(20) NOT NULL COMMENT '清单编号：O+YYYYMMDD+00001',
  `createTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `lastUpdateTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `status` varchar(10) DEFAULT NULL COMMENT '状态：0-待提交；1-已提交；T-套餐',
  `applyUserId` varchar(20) NOT NULL COMMENT '申请者',
  `deptId` varchar(32) NOT NULL COMMENT '部门ID',
  `areaCode` varchar(20) DEFAULT NULL COMMENT '地域代码',
  `platType` varchar(32) DEFAULT NULL COMMENT '平台类型',
  `deployType` varchar(20) DEFAULT NULL COMMENT '部署类型',
  `envCode` varchar(20) DEFAULT NULL COMMENT '环境代码',
  `resType` varchar(20) DEFAULT NULL COMMENT '资源类型',
  `virName` varchar(60) DEFAULT NULL COMMENT '虚拟机名称',
  `virIp` varchar(20) DEFAULT NULL COMMENT '虚拟机IP',
  `cpu` varchar(10) DEFAULT NULL COMMENT 'CPU',
  `memory` varchar(10) DEFAULT NULL COMMENT '内存',
  `diskType` varchar(3000) DEFAULT NULL COMMENT '磁盘类型，多个用英文逗号分隔',
  `diskSize` varchar(3000) DEFAULT NULL COMMENT '磁盘大小，多个用英文逗号分隔',
  `diskEncrypt` varchar(3000) DEFAULT NULL COMMENT '磁盘加密，多个用英文逗号分隔',
  `softCode` varchar(3000) DEFAULT NULL COMMENT '软件代码，多个用英文逗号分隔',
  `softParam` varchar(3000) DEFAULT NULL COMMENT '软件参数，多个用英文逗号分隔',
  `projectCode` varchar(32) DEFAULT NULL COMMENT '项目代码',
  `osType` varchar(20) DEFAULT NULL COMMENT '操作系统类型',
  `osBitNum` varchar(10) DEFAULT NULL COMMENT '操作系统位数',
  `imgCode` varchar(20) DEFAULT NULL COMMENT '镜像代码',
  `imgUserName` varchar(60) DEFAULT NULL COMMENT '镜像用户名',
  `imgUserPass` varchar(60) DEFAULT NULL COMMENT '镜像用户密码',
  `imgPath` varchar(300) DEFAULT NULL COMMENT '镜像路径',
  `expireDate` varchar(19) DEFAULT NULL COMMENT '到期时间',
  `virNum` varchar(10) DEFAULT NULL COMMENT '虚拟机数量',
  `totalAmt` varchar(20) DEFAULT NULL COMMENT '总价格',
  `fileName` varchar(200) DEFAULT NULL COMMENT '文件名',
  `pckgName` varchar(60) DEFAULT NULL COMMENT '套餐名称',
  PRIMARY KEY (`orderNo`),
  KEY `indx_cmp_order_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='清单表';